# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_abandoned_carts:
    class: Cart::CleanupJob
    schedule: every day at 4am
  expire_unpaid_card_orders:
    class: Order::ExpireUnpaidCardJob
    schedule: every hour at minute 25
  remind_appointments:
    class: Appointment::ReminderJob
    schedule: every hour at minute 5
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
